version: '3.7'

services:
  memo:
    container_name: memo-service
    build:
      context: .
      target: development
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:3000
      - 9229:9229
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    container_name: memo-postgres
    image: postgres:12
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    container_name: memo-rabbitmq
    image: rabbitmq:3.11-management-alpine
    env_file:
      - .env
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq

networks:
  default:
    name: memo
    #external: true

volumes:
  pgdata:
  rabbitmq:
    driver: local
